var annotated_dup =
[
    [ "cfgfile", "namespacecfgfile.html", [
      [ "details", "namespacecfgfile_1_1details.html", [
        [ "determine_format_t", "classcfgfile_1_1details_1_1determine__format__t.html", "classcfgfile_1_1details_1_1determine__format__t" ],
        [ "parser_base_t", "classcfgfile_1_1details_1_1parser__base__t.html", "classcfgfile_1_1details_1_1parser__base__t" ],
        [ "parser_conffile_impl_t", "classcfgfile_1_1details_1_1parser__conffile__impl__t.html", "classcfgfile_1_1details_1_1parser__conffile__impl__t" ],
        [ "parser_dom_impl_t", "classcfgfile_1_1details_1_1parser__dom__impl__t.html", "classcfgfile_1_1details_1_1parser__dom__impl__t" ]
      ] ],
      [ "const_t", "structcfgfile_1_1const__t.html", null ],
      [ "constraint_min_max_t", "classcfgfile_1_1constraint__min__max__t.html", "classcfgfile_1_1constraint__min__max__t" ],
      [ "constraint_one_of_t", "classcfgfile_1_1constraint__one__of__t.html", "classcfgfile_1_1constraint__one__of__t" ],
      [ "constraint_t", "classcfgfile_1_1constraint__t.html", "classcfgfile_1_1constraint__t" ],
      [ "exception_t", "classcfgfile_1_1exception__t.html", "classcfgfile_1_1exception__t" ],
      [ "exception_t< string_trait_t >", "classcfgfile_1_1exception__t_3_01string__trait__t_01_4.html", "classcfgfile_1_1exception__t_3_01string__trait__t_01_4" ],
      [ "format_t", "classcfgfile_1_1format__t.html", null ],
      [ "format_t< bool, Trait >", "classcfgfile_1_1format__t_3_01bool_00_01_trait_01_4.html", null ],
      [ "format_t< double, qstring_trait_t >", "classcfgfile_1_1format__t_3_01double_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< double, string_trait_t >", "classcfgfile_1_1format__t_3_01double_00_01string__trait__t_01_4.html", null ],
      [ "format_t< double, wstring_trait_t >", "classcfgfile_1_1format__t_3_01double_00_01wstring__trait__t_01_4.html", null ],
      [ "format_t< int, qstring_trait_t >", "classcfgfile_1_1format__t_3_01int_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< int, string_trait_t >", "classcfgfile_1_1format__t_3_01int_00_01string__trait__t_01_4.html", null ],
      [ "format_t< int, wstring_trait_t >", "classcfgfile_1_1format__t_3_01int_00_01wstring__trait__t_01_4.html", null ],
      [ "format_t< long long, qstring_trait_t >", "classcfgfile_1_1format__t_3_01long_01long_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< long long, string_trait_t >", "classcfgfile_1_1format__t_3_01long_01long_00_01string__trait__t_01_4.html", null ],
      [ "format_t< long long, wstring_trait_t >", "classcfgfile_1_1format__t_3_01long_01long_00_01wstring__trait__t_01_4.html", null ],
      [ "format_t< long, qstring_trait_t >", "classcfgfile_1_1format__t_3_01long_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< long, string_trait_t >", "classcfgfile_1_1format__t_3_01long_00_01string__trait__t_01_4.html", null ],
      [ "format_t< long, wstring_trait_t >", "classcfgfile_1_1format__t_3_01long_00_01wstring__trait__t_01_4.html", null ],
      [ "format_t< QString, qstring_trait_t >", "classcfgfile_1_1format__t_3_01_q_string_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< QString, string_trait_t >", "classcfgfile_1_1format__t_3_01_q_string_00_01string__trait__t_01_4.html", null ],
      [ "format_t< QString, wstring_trait_t >", "classcfgfile_1_1format__t_3_01_q_string_00_01wstring__trait__t_01_4.html", null ],
      [ "format_t< std::string, qstring_trait_t >", "classcfgfile_1_1format__t_3_01std_1_1string_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< std::string, wstring_trait_t >", "classcfgfile_1_1format__t_3_01std_1_1string_00_01wstring__trait__t_01_4.html", null ],
      [ "format_t< std::wstring, qstring_trait_t >", "classcfgfile_1_1format__t_3_01std_1_1wstring_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< std::wstring, string_trait_t >", "classcfgfile_1_1format__t_3_01std_1_1wstring_00_01string__trait__t_01_4.html", null ],
      [ "format_t< typename Trait::string_t, Trait >", "classcfgfile_1_1format__t_3_01typename_01_trait_1_1string__t_00_01_trait_01_4.html", null ],
      [ "format_t< unsigned int, qstring_trait_t >", "classcfgfile_1_1format__t_3_01unsigned_01int_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< unsigned int, string_trait_t >", "classcfgfile_1_1format__t_3_01unsigned_01int_00_01string__trait__t_01_4.html", null ],
      [ "format_t< unsigned int, wstring_trait_t >", "classcfgfile_1_1format__t_3_01unsigned_01int_00_01wstring__trait__t_01_4.html", null ],
      [ "format_t< unsigned long long, qstring_trait_t >", "classcfgfile_1_1format__t_3_01unsigned_01long_01long_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< unsigned long long, string_trait_t >", "classcfgfile_1_1format__t_3_01unsigned_01long_01long_00_01string__trait__t_01_4.html", null ],
      [ "format_t< unsigned long long, wstring_trait_t >", "classcfgfile_1_1format__t_3_01unsigned_01long_01long_00_01wstring__trait__t_01_4.html", null ],
      [ "format_t< unsigned long, qstring_trait_t >", "classcfgfile_1_1format__t_3_01unsigned_01long_00_01qstring__trait__t_01_4.html", null ],
      [ "format_t< unsigned long, string_trait_t >", "classcfgfile_1_1format__t_3_01unsigned_01long_00_01string__trait__t_01_4.html", null ],
      [ "format_t< unsigned long, wstring_trait_t >", "classcfgfile_1_1format__t_3_01unsigned_01long_00_01wstring__trait__t_01_4.html", null ],
      [ "input_stream_t", "classcfgfile_1_1input__stream__t.html", "classcfgfile_1_1input__stream__t" ],
      [ "lexeme_t", "classcfgfile_1_1lexeme__t.html", "classcfgfile_1_1lexeme__t" ],
      [ "lexical_analyzer_t", "classcfgfile_1_1lexical__analyzer__t.html", "classcfgfile_1_1lexical__analyzer__t" ],
      [ "parser_info_t", "classcfgfile_1_1parser__info__t.html", "classcfgfile_1_1parser__info__t" ],
      [ "parser_t", "classcfgfile_1_1parser__t.html", "classcfgfile_1_1parser__t" ],
      [ "qstring_trait_t", "structcfgfile_1_1qstring__trait__t.html", "structcfgfile_1_1qstring__trait__t" ],
      [ "qstring_wrapper_t", "classcfgfile_1_1qstring__wrapper__t.html", "classcfgfile_1_1qstring__wrapper__t" ],
      [ "string_trait_t", "structcfgfile_1_1string__trait__t.html", "structcfgfile_1_1string__trait__t" ],
      [ "tag_no_value_t", "classcfgfile_1_1tag__no__value__t.html", "classcfgfile_1_1tag__no__value__t" ],
      [ "tag_scalar_t", "classcfgfile_1_1tag__scalar__t.html", "classcfgfile_1_1tag__scalar__t" ],
      [ "tag_scalar_t< bool, Trait >", "classcfgfile_1_1tag__scalar__t_3_01bool_00_01_trait_01_4.html", "classcfgfile_1_1tag__scalar__t_3_01bool_00_01_trait_01_4" ],
      [ "tag_scalar_t< QString, Trait >", "classcfgfile_1_1tag__scalar__t_3_01_q_string_00_01_trait_01_4.html", "classcfgfile_1_1tag__scalar__t_3_01_q_string_00_01_trait_01_4" ],
      [ "tag_scalar_t< typename Trait::string_t, Trait >", "classcfgfile_1_1tag__scalar__t_3_01typename_01_trait_1_1string__t_00_01_trait_01_4.html", "classcfgfile_1_1tag__scalar__t_3_01typename_01_trait_1_1string__t_00_01_trait_01_4" ],
      [ "tag_scalar_vector_t", "classcfgfile_1_1tag__scalar__vector__t.html", "classcfgfile_1_1tag__scalar__vector__t" ],
      [ "tag_t", "classcfgfile_1_1tag__t.html", "classcfgfile_1_1tag__t" ],
      [ "tag_vector_of_tags_t", "classcfgfile_1_1tag__vector__of__tags__t.html", "classcfgfile_1_1tag__vector__of__tags__t" ],
      [ "wstring_trait_t", "structcfgfile_1_1wstring__trait__t.html", "structcfgfile_1_1wstring__trait__t" ]
    ] ]
];